### ISSUE TITLE
Request for CZMQ version requirement clarification on readme

### ISSUE THREAD

**Issue by joegsn** [paddor/czmq-ffi-gen#1]
The version requirement for CZMQ says > 3.0 (master).  I assumed this meant that 3.0.2 would work, but it doesn't.  I don't know how you could write it cleaner, I just know I spent a few hours trying to understand a few things, before realizing that the "release" version of CZMQ isn't compatible with czmq-ffi-gen-0.8.3.
## 

I was originally going to write an issue that zlistx_head & zlistx_tail weren't found in czmq as there as these error messages are generated (there would be a duplicate for zlistx_tail):

```
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ffi-1.9.10/lib/ffi/library.rb:261:in 'attach_function': Function 'zlistx_head' not found in [/usr/local/lib/libczmq.dylib] (FFI::NotFoundError)
    from /opt/local/lib/ruby2.2/gems/2.2.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/czmq/ffi.rb:410:in '<module:FFI>'
    from /opt/local/lib/ruby2.2/gems/2.2.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/czmq/ffi.rb:10:in '<module:CZMQ>'
    from /opt/local/lib/ruby2.2/gems/2.2.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen/czmq/ffi.rb:9:in '<top (required)>'
    from /opt/local/lib/ruby2.2/gems/2.2.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen.rb:1:in 'require_relative'
    from /opt/local/lib/ruby2.2/gems/2.2.0/gems/czmq-ffi-gen-0.8.3/lib/czmq-ffi-gen.rb:1:in '<top (required)>'
    from /opt/local/lib/ruby2.2/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
    from /opt/local/lib/ruby2.2/2.2.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
    from /opt/local/lib/ruby2.2/gems/2.2.0/gems/cztop-0.4.0/lib/cztop.rb:1:in '<top (required)>'
    from /opt/local/lib/ruby2.2/2.2.0/rubygems/core_ext/kernel_require.rb:128:in 'require'
    from /opt/local/lib/ruby2.2/2.2.0/rubygems/core_ext/kernel_require.rb:128:in 'rescue in require'
    from /opt/local/lib/ruby2.2/2.2.0/rubygems/core_ext/kernel_require.rb:39:in 'require'
```

Then I realized that I was also missing out on some functionality I expected, like the new ZMQ Client/Server protocol socket types.  I had not realized that the 3.0.2 release of CZMQ would not support all of that functionality.

It seems to me that perhaps something similar to the begin-rescue code used around the zsock_new_server code could be utilized around the zlistx_head/tail code to make czmq-ffi-gen compatible with 3.0.2.  Though obviously many would like the new functionality exposed from newer versions of czmq, so even just documentation suggesting to use a newer version than 3.0.2 would be a great solution.

**Comment by paddor** [comment]
Sorry for the inconvenience, but I think the README clearly states that you'll have to use CZMQ from master.

> Note: The option --HEAD is required because this binding is generated directly from CZMQ's master branch. The current and older releases aren't supported.

Plus, to me, the version requirement "> 3.0" does NOT include "3.0.2", because the latter is just a bugfix release of the first's release line. "> 3.0" would mean "3.1" or "4.0". I'll adapt the README though.
